# Generated by Django 4.2.10 on 2024-03-20 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradeapp', '0003_pic_delete_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pic',
        ),
    ]
